// <auto-generated />
namespace Order_Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class order_application_setup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(order_application_setup));
        
        string IMigrationMetadata.Id
        {
            get { return "202102280325170_order_application_setup"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
