// <auto-generated />
namespace Order_Application.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class product_extentionpath : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(product_extentionpath));
        
        string IMigrationMetadata.Id
        {
            get { return "202103020313383_product_extentionpath"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
